### ISSUE TITLE
Please consider adding a screenshot

### ISSUE THREAD

**Issue by Infirme** [Kalk88/Borland-Theme#1]
Hello,

Borland-Theme is one of my favorite themes for VS Code. But I have to say, I would normally **never** install a theme that doesn't have a screenshot in its description. To me, it would be as absurd as downloading a font or a wallpaper that doesn't have any preview picture. Or buying online a hat or a shirt that doesn't have any product photo. I made an exception for Borland-Theme just because of my Borland nostalgia, and I am sincerely glad I did. Anyway, please consider adding a screenshot.

**Comment by simondmansson** [comment]
Thanks for your comments, screenshot Added! I even updated the background color on the sidebar and activity bar. You are always welcome to make a pull request if you have any improvements in mind, or fork it and make your own version.
![nickleback](https://media.giphy.com/media/RHPxe7KPnb8KaAtBbE/giphy.gif)

**Comment by Infirme** [comment]
Not only meeting my expectation, but exceeding it. Perfect! Have a great week-end!
